Вёрстка модального окна "Заказ - достаточно баллов"
Jarpes/Kolesa-Upgrade-FE-2021 pull request #2
Opened 2021-09-26 16:49 UTC by Jarpes

2021-09-26 20:36 UTC, AlexPavlof requested changes

2021-09-26 20:36 UTC, AlexPavlof commented on src/assets/pointBalance.svg
> +<svg width="40" height="41" viewBox="0 0 40 41" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Выглядит, как растровое изображение, в обёртке svg. Может, сразу в png экспортировать?

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    background: url('/src/assets/close.svg') no-repeat;
Как правило, ссылки в файлах CSS делаются относительными. 

1. Современные IDE умеют следить за изменением структуры файлов, например, если завтра потребуется переместить изображение в другое место. В данном же случае скорее всего придётся менять пути вручную. 

2. К тому же не уверен, что будет работать переход по файлам, так как для unix-like систем /src/...... означает, что поиск нужно производить от корневого каталога.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    padding: 11px;
Если выбрать в Фигме крестик, то видно, что у него странные размеры и странные отступы. Но по факту — это не кнопка, выбрита только иконка

<img width="109" alt="image" src="https://user-images.githubusercontent.com/1210257/134820210-2a658efe-14d8-499e-bbb2-4e25a9ee0433.png">
В палитре слева можно выбрать слой, который содержит эту иконку, и тогда всё встанет на свои места.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    padding: 11px;
Размер блока задаётся через ширину/высоту. padding для этого не самое подходящее решение, как минимум оно не очевидно.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +.btn-close {
Ссылка должна быть ссылкой, а кнопка должна быть кнопкой. По факту — это кнопка (`button`), но в коде оформлена как ссылка (`a`).

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    top: 20%;
Не понятно, откуда взялись 20%.
На мониторе ноутбука страница выглядит примерно так:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1210257/134820383-a1b31a8a-ce6b-46cd-891c-af4fe4c9f42b.png">

Существует несколько хороших и проверенных способов размещения уборка по центру экрана. Лучше воспользоваться одним из них.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    -webkit-transform: translate(0, 0);
Если зайти Can I Use (https://caniuse.com/?search=transform) и посмотреть на поддержку, можно увидеть, что современные браузеры поддерживают это свойство без префиксов.

Это не входит в рамки задачи, но в живом проекте старайся автоматизировать такую рутину. Помнить поддержку всех свойств наизусть нереально, а каждый раз заходить на caniuse долго. Существуют специальные утилиты, которые позволяют автоматически подставлять необходимые префиксы, исходя из текущей поддержки браузеров. Как правило это происходит на этапе сборки бандла проекта. Можно подробнее почитать про [PostCSS](https://postcss.org) и [Authprefixer](https://github.com/postcss/autoprefixer).

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    border: #333 solid 0;
Не нашёл этого в макете. С какой-то конкретной целью сделано?

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin: 0 auto;
Блок позиционирован абсолютно, поэтому эффекта данное свойство не сделает никакого.

2021-09-26 20:36 UTC, AlexPavlof commented on src/js/main.js
> +<div class="modal opened" aria-hidden="true">
В данном случае вёрстку нужно перенести напрямую в HTML

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-left: -520px;
Модальные окна могут быть разного размера. Отцентровать их можно с помощью `transform: translate(-50%, -50%)` или для данного случая можно отцентровать только по оси X `transform: translateX(-50%)`.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    font-family: Open sans, sans-serif;
Вроде бы Open Sans, но по факту — системный шрифт.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1210257/134821706-d9137de3-1e29-48f5-ba06-06231729250a.png">

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    padding-right: 7px;
В макете другое значение

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +.preview-additional {
По факту элементы в блоке расположены не по центру, а смещены на 7px влево.
<img width="358" alt="image" src="https://user-images.githubusercontent.com/1210257/134822038-b6b0ba00-7678-40a3-aadd-d810abada9c3.png">

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +.preview-additional {
Кстати, обрати внимание, что высота блока — 53px. Знаешь почему?

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    padding-bottom: 8px;
Не понятно, зачем этот отступ снизу?

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    line-height: 14px;
Думаю, тут стоит перепроверить значение. Как правило, высота строки больше размера шрифта. В макете так.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    font-style: normal;
Если свойство не было переопределено, то данная строка лишняя

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    font-style: normal;
Если свойство не было переопределено, то данная строка лишняя

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    line-height: 14px;
<img width="213" alt="image" src="https://user-images.githubusercontent.com/1210257/134822462-5789b566-3649-48fa-b7aa-49e48892371d.png">
По умолчанию у заголовков есть отступы сверху и снизу в 1em. Можно их обнулить, тогда выстраивать вёрстку будет проще.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-top: -7px;
После того, как уберёшь отступы у элементов h3, тут можно будет добавить нормальное значение, не отрицательное

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    padding-top: 10px;
Кнопка, пожалуй, самый удобный элемент, в котором не нужно дополнительно заботиться о центрировании текста. Достаточно задать ширину и высоту. Можно предположить, что кнопка будет переиспользована в другом месте и задать вместо конкретной ширины — минимальную.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    position: fixed;
Относительно какого блока выравнивается элемент? И почему?

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-top: 12px;
Если посмотреть на отступы в макете, то они имеют конкретные значения. Высота строки играет роль.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-top: 31px;
26, 18, 22, 31. У тебя получилось четыре варианта отступов для заголовков. По факту же в макете он один, но другого размера.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-top: 31px;
Старайся находить блоки, одинаковые по оформлению. В данном случае можно обойтись двумя вариантами: для выбора параметров и для описания.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    display: inline-block;
`inline-block` наследует проблему `inline` элементов — пробел между элементами. Поэтому ниже ты добавляешь отступ в 3px вместо 8px по макету. Проблема только заключается в том, что пробел не имеет конкретной ширины. Всё зависит от шрифта. Поэтому лучше для вёрстки таких блоков использовать другие значения display.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-bottom: 8px;
Кажется, не нужный отступ снизу

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-top: -1px;
Нужно будет поменять на нормальное значение, когда обнулишь отступы у заголовков.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-top: -2px;
Нужно будет поменять на нормальное значение, когда обнулишь отступы у заголовков.

2021-09-26 20:36 UTC, AlexPavlof commented on src/css/style.css
> +    margin-top: 31px;
Кстати, использовать `h3` для абсолютно всех заголовков — неправильно. И с точки зрения SEO, и с точки зрения семантики. У них получается одинаковый вес и смысл, по сути же разный.

2021-09-27 06:19 UTC, AlexPavlof approved these changes
Исправлены не все замечания

2021-09-28 04:40 UTC, Jarpes commented on src/css/style.css
> +    -webkit-transform: translate(0, 0);
Большое спасибо за очень подробное ревью, буду работать над своим кодом

2021-09-28 04:41 UTC, merged